services:
  - type: web
    name: streamtex
    runtime: docker
    repo: https://github.com/nicolasguelfi/streamtex-docs
    branch: main
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: FOLDER
        value: manuals/stx_manuals_collection
      - key: STX_URL_TEST_INTRO
        value: https://streamtex-intro.onrender.com
      - key: STX_URL_TEST_ADVANCED
        value: https://streamtex-advanced.onrender.com
      - key: STX_URL_TEST_DEPLOY
        value: https://streamtex-deploy.onrender.com
      - key: STX_PASSWORD
        value: changeme
    healthCheckPath: /_stcore/health

  - type: web
    name: streamtex-intro
    runtime: docker
    repo: https://github.com/nicolasguelfi/streamtex-docs
    branch: main
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: FOLDER
        value: manuals/stx_manual_intro
      - key: STX_PASSWORD
        value: changeme
    healthCheckPath: /_stcore/health

  - type: web
    name: streamtex-advanced
    runtime: docker
    repo: https://github.com/nicolasguelfi/streamtex-docs
    branch: main
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: FOLDER
        value: manuals/stx_manual_advanced
      - key: STX_PASSWORD
        value: changeme
    healthCheckPath: /_stcore/health

  - type: web
    name: streamtex-deploy
    runtime: docker
    repo: https://github.com/nicolasguelfi/streamtex-docs
    branch: main
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: FOLDER
        value: manuals/stx_manual_deploy
      - key: STX_PASSWORD
        value: changeme
    healthCheckPath: /_stcore/health
