[logger]
level = "error"

[client]
showErrorDetails = true

[theme]
base = "dark"
primaryColor = "#8B5CF6"
backgroundColor = "#111111"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"

[server]
enableStaticServing = true
