"""Atomic block — Support and configuration files."""

from streamtex import *
from streamtex.enums import Tags as t
from custom.styles import Styles as s
from blocks.helpers import show_code, show_explanation, show_details


class BlockStyles:
    """Support files section styles."""
    heading = s.project.titles.section_title + s.center_txt
    sub = s.project.titles.section_subtitle
    file_label = s.large + s.text.weights.bold_weight + s.project.colors.dev_green

bs = BlockStyles


def build():
    with st_block(s.center_txt):
        st_write(bs.heading, "Support & Configuration Files", tag=t.div, toc_lvl="1")
        st_space("v", 2)

        show_explanation("""\
            Beyond the source code, the repository includes configuration files for
            building, testing, linting, CI/CD, and dependency management. These files
            are essential for contributor workflow.
        """)
        st_space("v", 2)

        # --- pyproject.toml ---
        st_write(bs.sub, "pyproject.toml", toc_lvl="+1")
        st_space("v", 1)

        show_explanation("""\
            The single source of truth for project metadata, dependencies, build
            system configuration, and tool settings.
        """)
        st_space("v", 1)

        show_code("""\
            [project]
            name = "streamtex"
            version = "X.Y.Z"
            requires-python = ">=3.11"

            [build-system]
            requires = ["hatchling"]
            build-backend = "hatchling.build"

            [tool.ruff]          # Linting & formatting rules
            [tool.pytest.ini_options]  # Test configuration\
        """, language="toml")
        st_space("v", 1)

        show_details("""\
            Key sections: `[project]` for metadata and dependencies,
            `[build-system]` for hatchling, `[tool.ruff]` for linting rules
            (line length, ignored rules, per-file overrides), and
            `[tool.pytest.ini_options]` for test discovery and markers.
        """)
        st_space("v", 2)

        # --- GitHub Actions ---
        st_write(bs.sub, ".github/workflows/", toc_lvl="+1")
        st_space("v", 1)

        show_code("""\
            .github/workflows/
            ├── ci.yml       # Runs on every PR: lint, test, type-check
            └── publish.yml  # Triggered on tag push: build & publish to PyPI\
        """, language="text")
        st_space("v", 1)

        show_explanation("""\
            `ci.yml` runs ruff check, pytest, and optionally mypy on every pull
            request. `publish.yml` is triggered by version tags (e.g. `vX.Y.Z`)
            and handles the full PyPI release pipeline.
        """)
        st_space("v", 2)

        # --- .python-version ---
        st_write(bs.sub, ".python-version", toc_lvl="+1")
        st_space("v", 1)

        show_explanation("""\
            Pins the exact Python version used for development. Read by `uv` and
            pyenv to ensure all contributors use the same interpreter.
        """)
        st_space("v", 1)

        show_code("3.12", language="text")
        st_space("v", 2)

        # --- .gitattributes ---
        st_write(bs.sub, ".gitattributes", toc_lvl="+1")
        st_space("v", 1)

        show_explanation("""\
            Configures Git LFS tracking for large binary files (images, fonts,
            diagram outputs) to keep the repository lean.
        """)
        st_space("v", 2)

        # --- CHANGELOG.md ---
        st_write(bs.sub, "CHANGELOG.md", toc_lvl="+1")
        st_space("v", 1)

        show_explanation("""\
            Version history following the Keep a Changelog format. Each release
            section lists Added, Changed, Fixed, and Removed items. Updated as
            part of the release process.
        """)
        st_space("v", 1)

        show_code("""\
            ## [X.Y.Z] - YYYY-MM-DD
            ### Added
            - New feature description

            ### Fixed
            - Bug fix description\
        """, language="markdown")
        st_space("v", 2)

        # --- LICENSE ---
        st_write(bs.sub, "LICENSE", toc_lvl="+1")
        st_space("v", 1)

        show_explanation("MIT License — permissive open-source license.")
        st_space("v", 2)

        # --- uv.lock ---
        st_write(bs.sub, "uv.lock", toc_lvl="+1")
        st_space("v", 1)

        show_explanation("""\
            Lock file generated by `uv`. Pins every transitive dependency to an
            exact version, ensuring fully reproducible installs across all
            environments. Committed to the repository.
        """)
        st_space("v", 2)

        # --- README.md ---
        st_write(bs.sub, "README.md", toc_lvl="+1")
        st_space("v", 1)

        show_explanation("""\
            Project overview, installation instructions, quick-start guide, and
            links to the full documentation. This is the first thing contributors
            and users see on GitHub.
        """)
        st_space("v", 2)

        show_details("""\
            All configuration is centralised in `pyproject.toml` — there are no
            separate `setup.cfg`, `tox.ini`, or `.flake8` files. This keeps the
            repository root clean and makes onboarding straightforward.
        """)
