[logger]
level = "error"

[client]
showErrorDetails = true

[theme]
base = "dark"
primaryColor = "#667eea"
backgroundColor = "#111111"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
port = 8501
address = "0.0.0.0"
enableStaticServing = true
headless = false
runOnSave = true
