"""Prepare a custom mapping artefact for a pack — strict-separation pattern."""

from streamtex import st_block, st_code, st_space, st_write
from streamtex.enums import Tags as t
from custom.styles import Styles as s
from streamtex_design.design_systems.default import DesignSystem
from streamtex_design.components.callout import callout
from streamtex_design.components.comparison_table import comparison_table


DS = DesignSystem()


class BlockStyles:
    heading = s.project.titles.section_title + s.center_txt
    sub = s.project.titles.section_subtitle
    body = s.large
    code_box = s.container.paddings.small_padding + s.container.borders.solid_border


bs = BlockStyles


SKILL_TEMPLATE = """\
---
name: import-streamtex-design-mapping
description: Refactor low-level StreamTeX code imported by /stx-import:*
  commands towards the streamtex-design pack's components.
---

# Mapping rules (HTML/Marp/LaTeX → streamtex-design components)

This skill is **user-prepared** and **pack-specific**. It augments the
shared `/stx-import:*` commands (which produce pack-agnostic code)
with a refactor pass that maps recurring patterns onto the
streamtex-design pack's components.

## Inventory: components available in streamtex-design

Run `stx component list --pack streamtex-design` and quote the result
here, then keep the list up-to-date with your active pack version.

## Mapping table

| Imported pattern                          | streamtex-design component |
|-------------------------------------------|----------------------------|
| `<div class="callout-info">...</div>`     | `callout(kind="info", ...)` |
| Two-column compare layout                 | `comparison_table(...)`    |
| `<h1>` block-cover slide                  | `title_slide(...)`         |
| Three-card hero row                       | `card_grid(items=[...])`   |
| `<dl><dt>...<dd>...` definition list      | `term_definition_list(...)` |

## Workflow

1. Run a `/stx-import:*` command — produces low-level StreamTeX code.
2. Run the refactor command (`/refactor-streamtex-design`) that
   consumes this skill and the mapping table above.
3. Review the diff, run `stx validate --strict`.
"""


COMMAND_TEMPLATE = """\
---
name: refactor-streamtex-design
description: Refactor blocks generated by /stx-import:* towards the
  streamtex-design pack's components, using import-streamtex-design-mapping.
---

You will refactor StreamTeX block code towards the streamtex-design
pack. Read first:

1. `import-streamtex-design-mapping` skill (mapping table + inventory).
2. The target block file (passed as argument).
3. The output of `stx component list --pack streamtex-design`.

Then:

- For every pattern in the mapping table, replace the literal HTML/
  Style construction with a call to the corresponding component.
- Preserve `INVARIANTS` of each component (read its docstring via
  `stx component show <name>`).
- Run `stx validate` after refactoring.

If a recurring pattern is not in the mapping table, **propose** an
addition to the user before refactoring — do not invent mappings.
"""


def build():
    """Document the custom-import-mapping pattern (strict separation)."""
    st_write((bs.heading, "Custom import mapping"), toc_lvl="1", tag=t.div)
    st_space(10)
    st_write(
        bs.body + s.center_txt,
        "When importing HTML / Marp / LaTeX through the shared "
        "/stx-import:* commands and you want the resulting blocks to "
        "consume a pack's components, the StreamTeX doctrine is strict "
        "separation: the shared profile stays pack-agnostic, and you "
        "prepare a tiny custom skill + command pair to handle the "
        "mapping for your active pack. Once prepared, reuse it on every "
        "re-import.",
        tag=t.div,
    )
    st_space(20)

    # ---- 1) Why pack-agnostic ----
    st_write((bs.sub, "1 — Why pack-agnostic in the shared profile"), toc_lvl="+1", tag=t.div)
    st_space(10)
    st_write(
        bs.body,
        "The seven /stx-import:* commands (html, html-audit, marp, "
        "marp-analyze, latex, latex-analyze, pdf) produce low-level "
        "StreamTeX code with no knowledge of any pack. Two reasons:",
        tag=t.div,
    )
    st_space(10)
    callout(
        design_system=DS,
        variant="info",
        title="Doctrine: separation strict",
        body=(
            "Import and reuse architecture are orthogonal. The shared "
            "profile must not couple itself to any pack's component "
            "vocabulary."
        ),
    )
    st_space(10)
    callout(
        design_system=DS,
        variant="info",
        title="Scalability",
        body=(
            "Without this rule, the shared profile would grow "
            "proportionally with the ecosystem (one mapping table per "
            "pack). The user's custom artefacts scale with the user's "
            "choices instead."
        ),
    )
    st_space(20)

    # ---- 2) Custom skill ----
    st_write(
        (bs.sub, "2 — Custom skill: .claude/custom/skills/import-<pack>-mapping.md"),
        toc_lvl="+1", tag=t.div,
    )
    st_space(10)
    st_write(
        bs.body,
        "A markdown skill scoped to one pack, declaring the mapping "
        "table the AI agent consults during refactor:",
        tag=t.div,
    )
    st_space(10)
    with st_block(bs.code_box):
        st_code(code=SKILL_TEMPLATE, language="markdown")
    st_space(20)

    # ---- 3) Custom command ----
    st_write(
        (bs.sub, "3 — Custom command: .claude/custom/commands/refactor-<pack>/run.md"),
        toc_lvl="+1", tag=t.div,
    )
    st_space(10)
    st_write(
        bs.body,
        "A slash-command companion that reads the skill above and "
        "performs the refactor on a target block file:",
        tag=t.div,
    )
    st_space(10)
    with st_block(bs.code_box):
        st_code(code=COMMAND_TEMPLATE, language="markdown")
    st_space(20)

    # ---- 4) Concrete example ----
    st_write(
        (bs.sub, "4 — Concrete example: refactor towards streamtex-design"),
        toc_lvl="+1", tag=t.div,
    )
    st_space(10)
    with st_block(bs.code_box):
        st_code(
            code="""
# 1) Import a slide deck via the pack-agnostic shared command
/stx-import:marp slides/my-deck.md

# → produces blocks/bck_my_deck.py with low-level Style + st_block

# 2) Run the user-prepared refactor command for this pack
/refactor-streamtex-design blocks/bck_my_deck.py

# → reads .claude/custom/skills/import-streamtex-design-mapping.md
# → reads `stx component list --pack streamtex-design`
# → rewrites the block to call callout, card_grid, title_slide, ...

# 3) Validate
stx validate --strict
""",
            language="bash",
        )
    st_space(20)

    # ---- 5) Storage & conservation ----
    st_write((bs.sub, "5 — Storage and conservation"), toc_lvl="+1", tag=t.div)
    st_space(10)
    callout(
        design_system=DS,
        variant="info",
        title="Custom artefacts are owned by the user",
        body=(
            "Files in .claude/custom/ are NOT overwritten by stx claude "
            "update. Two conservation strategies, both supported:"
        ),
    )
    st_space(10)
    comparison_table(
        design_system=DS,
        columns=["Strategy", "Description"],
        rows=[
            ("Version in the project",
             "Commit .claude/custom/skills/import-<pack>-mapping.md and "
             ".claude/custom/commands/refactor-<pack>/ into the project's "
             "git repo. The mapping evolves alongside the blocks and the "
             "pack version. Good default for single-project work."),
            ("Archive once, reuse across projects",
             "Keep a personal .claude/custom/ snapshot in a side "
             "repository or dotfiles. Copy it into each new project after "
             "stx project new. Good for teams that import from the same "
             "pipeline across many projects."),
        ],
    )
    st_space(15)
    callout(
        design_system=DS,
        variant="success",
        title="Prepare once, reuse on every re-import",
        body=(
            "Either way: the shared /stx-import:* commands never need to "
            "know about your active pack."
        ),
    )
