"""Auto-generated BibRefs for IDE autocompletion.

Generated by:
    uv run python -m streamtex generate-stubs <files> -o <output.py>

Do not edit manually — regenerate when bibliography sources change.
"""

from streamtex.bib import cite


class _ProjectBibRefs:
    """Bibliography references with IDE autocompletion.

    Each property calls cite(key) and returns an HTML string
    for embedding in st_write().

    Unknown keys fall back to cite() dynamically (no completion).
    """

    @property
    def brown2020language(self) -> str:
        """Language Models are Few-Shot Learners — Brown et al. (2020)"""
        return cite("brown2020language")

    @property
    def devlin2019bert(self) -> str:
        """BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding — Devlin et al. (2019)"""
        return cite("devlin2019bert")

    @property
    def goodfellow2016deep(self) -> str:
        """Deep Learning — Goodfellow et al. (2016)"""
        return cite("goodfellow2016deep")

    @property
    def lecun2015deep(self) -> str:
        """Deep Learning — LeCun et al. (2015)"""
        return cite("lecun2015deep")

    @property
    def vaswani2017attention(self) -> str:
        """Attention Is All You Need — Vaswani et al. (2017)"""
        return cite("vaswani2017attention")

    def __getattr__(self, key: str) -> str:
        if key.startswith("_"):
            raise AttributeError(f"_ProjectBibRefs has no attribute '{key}'")
        return cite(key)


st_refs = _ProjectBibRefs()
