"""Media Overlays — native badge slot in st_image (MediaOverlay)."""

from blocks.helpers import show_code, show_details, show_explanation
from custom.styles import Styles as s
from streamtex import *
from streamtex.enums import Tags as t


class BlockStyles:
    """Media overlay demo styles."""
    heading = s.project.titles.section_title + s.center_txt
    sub = s.project.titles.section_subtitle
bs = BlockStyles


def build():
    with st_block(s.center_txt):
        st_write(bs.heading, "Media Overlays", tag=t.div, toc_lvl="1")
        st_space("v", 2)

        # --- 1. The native overlay slot ---
        st_write(bs.sub, "The native overlay slot", toc_lvl="+1")
        st_space("v", 1)

        show_explanation("""\
            **st_image()** can render a small badge *inside* the image's final
            display box via `overlay=MediaOverlay(...)`.

            The badge is emitted by the library at the exact point where the
            display width is known, so it follows the image box whatever the
            zoom, width or managed display settings — no external wrapper or
            offset computation needed.

            `overlay=None` (the default) keeps the emitted HTML strictly
            identical to previous versions.
        """)
        st_space("v", 1)

        show_code("""\
st_image(uri="sample_gradient.png", width="400px",
         alt="Gradient demo",
         overlay=MediaOverlay(text="✦ AI"))""")
        st_space("v", 1)

        st_image(uri="sample_gradient.png", width="400px",
                 alt="Gradient demo",
                 overlay=MediaOverlay(text="✦ AI"))
        st_space("v", 2)

        # --- 2. AI-transparency mark ---
        st_write(bs.sub, "AI-transparency mark", toc_lvl="+1")
        st_space("v", 1)

        show_explanation("""\
            The canonical use case is the **AI-transparency mark**: disclosing
            that an image is AI-generated (in the spirit of art. 50 of the EU
            AI Act). The mark is *overlaid* on the image, never burned into
            the pixels, and `aria_label` provides the accessible disclosure.

            Define the project convention once, then reuse it on every
            AI-generated image.
        """)
        st_space("v", 1)

        show_code("""\
AI_MARK = MediaOverlay(
    text="✦ AI",
    position="bottom-right",
    aria_label="This image was generated by an AI model",
    css="background:rgba(30,30,46,0.65); font-size:14px; padding:3px 10px;",
)

st_image(uri="sample_gradient.png", width="60%",
         alt="AI-generated illustration",
         overlay=AI_MARK)""")
        st_space("v", 1)

        ai_mark = MediaOverlay(
            text="✦ AI",
            position="bottom-right",
            aria_label="This image was generated by an AI model",
            css="background:rgba(30,30,46,0.65); font-size:14px; padding:3px 10px;",
        )
        st_image(uri="sample_gradient.png", width="60%",
                 alt="AI-generated illustration",
                 overlay=ai_mark)
        st_space("v", 2)

        # --- 3. Positions ---
        st_write(bs.sub, "Positions", toc_lvl="+1")
        st_space("v", 1)

        show_explanation("""\
            Four corner anchors are available: `bottom-right` (default),
            `top-right`, `bottom-left`, `top-left`.

            Prefer `top-right` when the media carries controls on its bottom
            edge (e.g. video players).
        """)
        st_space("v", 1)

        with st_grid(cols="repeat(auto-fit, minmax(280px, 1fr))",
                     grid_style=Style("gap:24px;", "media_overlay_gap")) as g:
            for _pos in ["bottom-right", "top-right", "bottom-left", "top-left"]:
                with g.cell():
                    st_image(uri="sample_gradient.png", width="100%",
                             alt=f"Overlay {_pos}",
                             overlay=MediaOverlay(text=_pos, position=_pos))
        st_space("v", 2)

        show_details("""\
            The badge never intercepts clicks (`pointer-events: none`), so a
            linked image (`link=`) stays fully clickable.

            `text` and `aria_label` are HTML-escaped at emission.

            The badge travels inside the image element in the HTML export —
            no post-processing needed.

            In editor mode (`editable=True`), the badge is rendered on the
            image only; the "Edit Image" panel stays outside the overlay box.

            Style is overridable via `css=` — declarations are appended after
            the default pill style, so they win in cascade order.
        """)
